site_name: dbt-score
theme:
  name: material
  logo: assets/medal.svg
  favicon: assets/medal.svg
  features:
    - content.code.copy # Copy button for code blocks
    - content.action.edit # Edit button pointing to Github
repo_url: https://github.com/PicnicSupermarket/dbt-score
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Get started: get_started.md
  - Create rules: create_rules.md
  - Package rules: package_rules.md
  - Configuration: configuration.md
  - Programmatic invocations: programmatic_invocations.md
  - Rules:
      - rules/generic.md
      - rules/macros.md
      - rules/filters.md
  - Reference:
      - reference/cli.md
      - reference/config.md
      - reference/dbt_utils.md
      - reference/exceptions.md
      - reference/evaluation.md
      - reference/models.md
      - reference/rule.md
      - reference/rule_registry.md
      - reference/scoring.md
      - Formatters:
          - reference/formatters/index.md
          - reference/formatters/human_readable_formatter.md
          - reference/formatters/manifest_formatter.md
          - reference/formatters/json_formatter.md
  - Contributor's guide: contributing.md
  - Changelog: https://github.com/PicnicSupermarket/dbt-score/blob/master/CHANGELOG.md
